# Generated by Django 3.2.9 on 2021-11-12 06:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstore_api.publisher'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_at',
            field=models.DateField(default=datetime.date(2021, 11, 12)),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_sells',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
    ]
