# Generated by Django 3.2.9 on 2021-11-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_api', '0004_alter_book_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='9783161484100', max_length=500),
        ),
    ]
