# Generated by Django 3.2.9 on 2021-11-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_api', '0006_alter_book_publish_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=500),
        ),
    ]
